apiVersion: apps/v1
kind: Deployment
metadata:
  name: japo-ambulance-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /japo-openapi
            - name: BASE_URL
              value: /japo-openapi-ui