apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
 name: japo-gitops-repo # v spoločnom klastri je nasadených viacero takýchto objektov
 namespace: wac-hospital
spec:
 interval: 1m0s
 ref:
     branch: main
 timeout: 1m0s
 url: https://github.com/kuko6/ambulance-gitops