apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: kuko6/ambulance-ufe
  newName: kuko6/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20240316.1151 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
- name: milung/ufe-controller
  newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
  newTag: 1.7.3 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
- name: kuko6/ambulance-wl-webapi
  newName: kuko6/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: main.20240506.0932 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
